M48
; DRILL file KiCad 10.0.6 date 2026-09-30T09:42:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-30T09:42:59+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X113.5Y-69.5
T2
X49.0Y-139.75
X49.25Y-69.75
X113.0Y-140.0
M30
